name: tpa
main: de.blaumeise03.tpa.TPA
version: 1.0-Release
description: A head database
api-version: 1.13
author: Blaumeise03
website: http://blaumeise03.de/

commands:
  tpa:
    description: Stell eine Teleportanfrage zu einem Spieler.
  tpaAccept:
    description: Akzeptiere eine Anfrage.
  tpaDeny:
    description: Lehne eine Anfrage ab.
permissions:
  tpa.tpa:
    description: Berechtingung für /tpa /tpaAccept und /tpaDeny
    default: true
  tpa.*:
    description: Wildcard permission
    default: op
    children:
      tpa.tpa: true