name: tpa
main: de.blaumeise03.tpa.TPA
version: 0.0-Snapshot

commands:
  tpa:
    description: Stell eine Teleportanfrage zu einem Spieler.
  tpaAccept:
    description: Akzeptiere eine Anfrage.
  tpaDeny:
    description: Lehne eine Anfrage ab.
permissions:
  tpa.tpa:
    description: Berechtingung für /tpa /tpaAccept und /tpaDeny
    default: true